trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Copy the built files from target folder
- task: CopyFiles@2
  inputs:
    contents: 'target/**'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

# Copy pom.xml explicitly to artifact staging directory
- task: CopyFiles@2
  inputs:
    contents: 'pom.xml'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

# Publish the artifact containing both build output and pom.xml
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
